version: '2'
services:
  golang_docker_kubernetes_api_service:
    build: ./api_service
#    networks:
#      - default
    expose:
    - "80"
    ports:
    - "8001:80"
  golang_docker_kubernetes_client_service:
    build: ./client_service
#    networks:
#      - default
    expose:
    - "80"
    ports:
    - "8080:80"
    links:
    - "golang_docker_kubernetes_api_service:golang_docker_kubernetes_api_service"
    environment:
      API: "http://golang_docker_kubernetes_api_service:80"
