version: '2'
services:
  client_service:
    build: ./client_service
    expose:
      - "80"
    ports:
      - "8080:80"
    links:
        - "api_service:api_service"
    environment:
      API: "http://api_service:80"
  api_service:
    build: ./api_service
    expose:
      - "80"
    ports:
      - "8001:80"