apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: api-service
    spec:
      containers:
        - name: api-service
          image: gcr.io/distelli-alpha/api-service:v1
